# cmp用docker部署的配置
version: "3.9"
services: 
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - D:\work_space\prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
    depends_on:
      - alertmanager

  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - D:\work_space\prometheus\alertmanager.yml:/etc/alertmanager/alertmanager.yml
